export {
  AGGRO_SAVED_DECK_ID,
  buildAggroSavedDeck,
  buildBuiltinDecks,
  buildBurnSavedDeck,
  buildComboMechanicalSavedDeck,
  buildControlSavedDeck,
  buildPrototypeSavedDeck,
  buildTempoSavedDeck,
  BURN_SAVED_DECK_ID,
  COMBO_MECHANICAL_SAVED_DECK_ID,
  CONTROL_SAVED_DECK_ID,
  isBuiltinDeckId,
  PROTOTYPE_SAVED_DECK_ID,
  TEMPO_SAVED_DECK_ID,
  withBuiltinDecks,
} from "./prototype.js";
