import { isAttribute, type Attribute } from "./attributes.js";
import type { CreatureId, DieId, PlayerId, SymbolInstanceId } from "./ids.js";

/**
 * A symbol a die or an effect can produce. There is no Shield symbol.
 */
export type SymbolType = Attribute;

export const isAttributeSymbol = (symbol: SymbolType): symbol is Attribute => isAttribute(symbol);

/**
 * The five states SPDD §16 requires the engine to tell apart. Collapsing these
 * into a count would make it impossible to honour the central rule that an
 * absorbed symbol never reaches engine resolution.
 *
 * There is deliberately no "stored" state. Bible §21 floated storing a symbol
 * and retaining a die as separate mechanics and asked for the terminology to be
 * standardized; only retaining a die survives, so nothing outlives the turn.
 *
 * `rolled` and `available` are the same unabsorbed pool for banking and Shield
 * absorb (playtest 2026-08-17). They remain distinct as provenance: die pips vs
 * effect-generated. ASSUMED in OPEN_DESIGN.md.
 */
export type SymbolStatus =
  /** Generated from a die this turn; unabsorbed pool. */
  | "rolled"
  /** Generated by an effect this turn; unabsorbed pool. */
  | "available"
  /** Taken by a creature; permanently out of engine resolution (bible §7). */
  | "absorbed"
  /** Held on a retained die rather than rerolled (bible §21). */
  | "retained"
  /** Spent. Kept in state so resource accounting is auditable. */
  | "consumed";

export interface SymbolInstance {
  readonly id: SymbolInstanceId;
  readonly ownerId: PlayerId;
  readonly symbol: SymbolType;
  readonly status: SymbolStatus;
  /** Null when an effect created the symbol rather than a die roll. */
  readonly sourceDieId: DieId | null;
  readonly absorbedByCreatureId: CreatureId | null;
  /**
   * When `false`, cannot bank as a usable attribute or count toward pile gates /
   * Spend (Decay unusable Corruption; resource-locked faces).
   * Omitted / `true` = usable. Spec `013`.
   */
  readonly usable?: boolean;
}

/**
 * Generic pile pips on a cost / gate / Spend (`{ any: 2 }`). Not a ninth
 * attribute, not Shield, and never a live resource after pile banking was
 * removed. Catalogue cost shapes may still use this bag.
 */
export const ANY_COST = "any";
export type AnyCostPip = typeof ANY_COST;

export const isAnyCostPip = (value: string): value is AnyCostPip => value === ANY_COST;

/**
 * A cost, e.g. `{ martial: 1, wild: 1 }` or `{ arcane: 1, any: 2 }`. Named
 * keys are attributes; `any` is a generic count of pile tokens of any
 * attribute. Shield is unrepresentable here rather than merely discouraged.
 */
export type SymbolRequirement = Readonly<Partial<Record<Attribute | AnyCostPip, number>>>;

/** A creature's absorbed fuel. Named attributes only — the pile never holds `any`. */
export type AttributeTokens = Readonly<Partial<Record<Attribute, number>>>;

/**
 * Rolled-face yield. Omitted face `pips` produces nothing.
 */
export type SymbolTokens = Readonly<Partial<Record<SymbolType, number>>>;

export const isSymbolType = (value: string): value is SymbolType => isAttribute(value);

/** Named symbol counts (`0` / omitted keys dropped). */
export const symbolTokenEntries = (
  tokens: SymbolTokens,
): ReadonlyArray<readonly [SymbolType, number]> =>
  Object.entries(tokens).flatMap(([symbol, count]) =>
    count === undefined || count <= 0 || !isSymbolType(symbol)
      ? []
      : [[symbol, count] as const],
  );

export const symbolTokenTotal = (tokens: SymbolTokens): number =>
  symbolTokenEntries(tokens).reduce((sum, [, count]) => sum + count, 0);

/** Named attribute counts on a requirement (`any` excluded). */
export const requirementEntries = (
  requirement: SymbolRequirement,
): ReadonlyArray<readonly [Attribute, number]> =>
  Object.entries(requirement).flatMap(([attribute, count]) =>
    count === undefined || count <= 0 || !isAttribute(attribute)
      ? []
      : [[attribute, count] as const],
  );

/** Generic (`Any`) pips on a requirement. `0` when omitted. */
export const genericCount = (requirement: SymbolRequirement): number =>
  Math.max(0, requirement[ANY_COST] ?? 0);

export const requirementTotal = (requirement: SymbolRequirement): number =>
  requirementEntries(requirement).reduce((total, [, count]) => total + count, 0) +
  genericCount(requirement);
