import { METRICS_SCHEMA_VERSION } from "./thresholds.js";
import type { MatchRecording, TurnRecord } from "./types.js";

const turn = (over: Partial<TurnRecord>): TurnRecord => ({
  turn: 1,
  playerId: "p1",
  startedAt: "2026-08-18T12:00:00.000Z",
  endedAt: "2026-08-18T12:01:00.000Z",
  durationMs: 60_000,
  actionCount: 4,
  rejectedCount: 0,
  damageDealt: 0,
  healAmount: 0,
  damagePrevented: 0,
  attacksDeclared: 0,
  cardsPlayed: 0,
  cardsDrawn: 0,
  forges: 0,
  cardsForged: 0,
  absorbs: 0,
  ritualActivations: 0,
  creaturesDefeated: 0,
  pendingDecisionOpens: 0,
  reactionWindows: 0,
  chainLinksAdded: 0,
  stall: true,
  hp: [],
  zonesByPlayer: {},
  ...over,
});

export function fakeRecording(over: Partial<MatchRecording> = {}): MatchRecording {
  const turns = over.turns ?? [turn({ turn: 1 }), turn({ turn: 2, playerId: "p2" })];
  return {
    schemaVersion: METRICS_SCHEMA_VERSION,
    recordingId: "rec-1",
    matchId: "match-1",
    startedAt: "2026-08-18T12:00:00.000Z",
    updatedAt: "2026-08-18T12:20:00.000Z",
    endedAt: "2026-08-18T12:20:00.000Z",
    status: "finished",
    recordedAs: "local",
    roomCode: null,
    localPlayerId: null,
    seed: 1,
    p1DeckId: "aggro",
    p2DeckId: "control",
    p1DeckName: "Aggro",
    p2DeckName: "Control",
    winnerId: "p1",
    firstPlayerId: "p1",
    totalTurns: 22,
    durationMs: 1_200_000,
    acceptedActions: 80,
    rejectedActions: 2,
    slowThinkCount: 4,
    stallTurnCount: 12,
    totalDamageDealt: 18,
    totalAttacksDeclared: 6,
    totalCardsPlayed: 10,
    totalCardsForged: 4,
    eventCounts: {
      "damage-dealt": 6,
      "attack-declared": 6,
      "reaction-priority-opened": 20,
    },
    cardPlayCounts: { "Eclipse (card-eclipse)": 2 },
    cardForgeCounts: { "Living Library (card-living-library)": 4 },
    pendingDecisionCounts: { "choose-creature": 8 },
    livingCreaturesAtEnd: { p1: 1, p2: 0 },
    hpRemainingAtEnd: { p1: 4, p2: 0 },
    turns,
    actions: [
      {
        seq: 0,
        at: "2026-08-18T12:00:01.000Z",
        deltaMs: 0,
        turn: 1,
        phase: "roll",
        playerId: "p1",
        actionType: "ROLL_DICE",
        accepted: true,
        errorCode: null,
        pendingDecisionType: null,
        chainDepth: 0,
        eventsAppended: 3,
        eventTypes: ["die-rolled"],
        reconstructed: false,
      },
      {
        seq: 1,
        at: "2026-08-18T12:00:25.000Z",
        deltaMs: 24_000,
        turn: 1,
        phase: "actions",
        playerId: "p1",
        actionType: "END_TURN",
        accepted: true,
        errorCode: null,
        pendingDecisionType: null,
        chainDepth: 0,
        eventsAppended: 2,
        eventTypes: ["turn-ended", "turn-started"],
        reconstructed: false,
      },
    ],
    ...over,
  };
}
